### ISSUE TITLE
several UI improvements

### ISSUE THREAD

**Issue by pmattern** [lxqt/obconf-qt#11]
Issue meant to summarize some improvements regarding the UI that I'd deem worth considering but not putting in an issue on its own:

The separator between left pane and the right part of the UI where the actual settings are made cannot be moved. As a consequence those "headers" at the left (Theme, Appearance, ...) are nearly always cut.
Thus I think it would be very good if that separator could e. g. be dragged horizontally.

ObConf-Qt still lacks a preview of themes.
Besides themes are applied at once by clicking I think a preview would be nice to have as it provides an overview of available themes.

Button "Close" can't be activated by a mnemonic (underlined letter that allows for activating by hitting Alt+<letter>).
Would it be feasible to implement this?

**Comment by PCMan** [comment]
Preview is hard to do with Qt 5. (easier in Qt4)
Openbox rendering code generates several small X11 pixmaps.
You have to composite them manually and generate a QPixmap, but Qt5 no longer wraps X11 pixmaps with QPixmap. So things becomes much more complicated.
This should be done with some XCB hacks and is not a trivial task.

**Comment by pmattern** [comment]
Considering that Openbox will probably never support Wayland and is likely to be dropped as preferred window manager of LXQt I think it shouldn't be put too much effort into its configuration tool ObConf-Qt any more either.
Maybe you can look into the two other items first and postpone or even drop that preview thing. I think the spacer position is a bit annoying but all the rest is far from being essential.
