### ISSUE TITLE
Theme does not change after selecting one from the list

### ISSUE THREAD

**Issue by MasterGeekMX** [lxqt/obconf-qt#131]
##### Expected Behavior
When clicking a theme on the theme list, the theme should be changed immediately

##### Current Behavior
Clicking a theme does nothing. the previous theme remains setted.

##### Steps to Reproduce (for bugs)

1. open `obconf-qt`
2. select a theme from the list

##### Context
Debian installation of LXQt does not include `obconf-qt`, but Lubuntu does, and i'm trying to mimitate the look'n'feel of it. After installing it from the repos (using testing so it's the current version) i found the issue.

##### System Information

* Distribution & Version: Debian Testing (installation of 10 (Buster) with testing repo enabled)
* Kernel: 5.4.0-3-amd64
* Qt Version: 5.12.5
* libqtxdg Version: 3.4.0-1
* lxqt-build-tools Version: 0.6.0-2
* Package version: 0.14.1

**Comment by agaida** [comment]
Strange - for me it works fine, so just closing - and please, if you think there is a bug in Debian, please file a bug in the Debian BTS. Not in this case, i would close it without further discussion. 

Mhh - btw, i don't know nothing about Debian but closing this anyways - works just fine for me.

**Comment by agaida** [comment]
Btw - i really don't buy it: http://pb.5id.eu/8ViY.mkv

**Comment by tsujan** [comment]
@agaida It works here too, as it did before. @MasterGeekMX may have a file permission problem or...

**Comment by agaida** [comment]
wild guess: `apt --no-install-recommends install lxqt-core` ...

**Comment by MasterGeekMX** [comment]
```
$ blame mastergeekmx
The user is an idiot.
$
```

It turns out (maybe because I'm in testing, maybe because of `tasksel` installing LXQt, maybe because of Debian) that the instalation that I had of LXQt had `xfwm4` for window manager instead of `Openbox`.

I noticed that because, sick of the problems, I deleted the install and did a fresh one, and when I installed obconf-qt it pulled out openbox as a dependency... And everything clicked.

**Comment by agaida** [comment]
Well, xfwm4 is the default WM for LXQt in Debian - apt show lxqt should show the line xfwm4 | x-window-manager :D

**Comment by MasterGeekMX** [comment]
For me its weird that debian opts to use xfwm4, considering that LXQt is a port of LXDE, and that project uses openbox as window manager.

**Comment by tsujan** [comment]
As we have repeatedly said, LXQt doesn't have a WM of its own but can work with any DE-agnostic WM.

As for choosing xfwm4 over openbox in Debian, it's quite understandable, considering that openbox doesn't have compositing, compton is a terrible compositor and we are in 2020. But you're free to change your WM to openbox.

**Comment by MasterGeekMX** [comment]
Blame on me. I'm basically recreating Lubuntu on a Debian VM and they use openbox.
