### ISSUE TITLE
obconf-qt not updated to 0.17.0

### ISSUE THREAD

**Issue by david-geiger** [lxqt/obconf-qt#172]
Hi,

Should obconf-qt not to be updated to the new recent release 0.17.0?

Regards,
David

**Comment by stefonarch** [comment]
https://github.com/lxqt/lxqt/discussions/1968#discussioncomment-621687

**Comment by tsujan** [comment]
Maybe a 0.16.1 isn't a bad idea. And if translations come, 0.16.2, 0.16.3,... showing that it can be used but is not developed anymore.

@stefonarch 
What do you think?

**Comment by stefonarch** [comment]
A 0.16.1 is a good idea, translations are [quite complete](https://github.com/lxqt/obconf-qt#translations) in most languages.
I think Ucranian, Bulgarian, Lithuanian and Norwegian are not present or not complete in the last release.

**Comment by tsujan** [comment]
I'll make it today.

**Comment by david-geiger** [comment]
So if obconf-qt and openbox are no more recommended/used upstream, what is the default window manager that we should recommended in a stable release? e.g: for us on Mageia distrib

**Comment by tsujan** [comment]
LXQt has never had a default WM. Distros are free to use any modular WM, Openbox included.

That will change with Wayland. When? No one seems to know yet.

**Comment by tsujan** [comment]
Done: https://github.com/lxqt/obconf-qt/releases/tag/0.16.1

**Comment by stefonarch** [comment]
Yeah, this should be done but after a few days, as it will be on top on the website. Let be on the top the release post for some time.

**Comment by tsujan** [comment]
I'll make a point release the day after tomorrow.
