### ISSUE TITLE
new windows (and popups) get focus even when "Focus new windows" is de-selected

### ISSUE THREAD

**Issue by gregrwm** [lxqt/obconf-qt#189]
##### Expected Behavior

Honor the option as presented.
True and complete prevention of focus stealing is needed to realistically do any typing.

##### Current Behavior

New windows always get focus.

##### Steps to Reproduce (for bugs)

1. de-select "Focus new windows when they appear"
2. (select "Focus windows when the mouse pointer moves over them")
3. (select "Move focus under the mouse when switching desktops")
4. launch something eg qterminal from either the appmenu or a terminal

##### Context

Without focus stealing prevention, new windows or popups interpose themselves into what a typist is typing, the new window receives keystrokes, and may well make selections and dismiss itself before the typist is even aware what happened.

##### System Information

* Distribution & Version: 2080235520 2021-11-08 Mon 19:56:32 lubuntu/jammy-desktop-amd64.iso
* Kernel: Linux lubuntu 5.13.0-19-generic SMP Thu Oct 7 21:58:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 
* libqtxdg Version: liblxqt0:amd64 (0.17.0-0ubuntu1)
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
If this is a bug, it's in openbox.
