### ISSUE TITLE
broken setting

### ISSUE THREAD

**Issue by Unixware** [lxqt/obconf-qt#191]
##### Current Behavior

The setting "Center new windows when they are placed" is not working,  I am checking it
new windows  are not "centered" on screen, also the box stays empty on the next launch of the obconf-qt.

##### Steps to Reproduce (for bugs)

1.  
2. 
3. 
4. 

##### System Information

* Distribution & Version:  Fedora 35 
* Kernel: 5.15xxx
* Qt Version: no effin idea
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:  obconf-qt --version does not display any "version" (half baked I assume)

**Comment by libalis** [comment]
I have the exact same issue, just wondering whether obconf-qt is still maintained at all?

**Comment by tsujan** [comment]
No, obconf-qt isn't developed anymore. LXQt is agnostic toward WMs.

**Comment by libalis** [comment]
I understand that lxqt is independent, it's still a shame that obconf-qt doesn't really work anymore.

**Comment by GreenLunar** [comment]
> I understand that lxqt is independent, it's still a shame that obconf-qt doesn't really work anymore.

I suggest you make yourself a developer and be a new contributor to obconf-qt.

**Comment by tsujan** [comment]
Fixed by https://github.com/lxqt/obconf-qt/pull/179

**Comment by GreenLunar** [comment]
Thank you (:

**Comment by zhrexl** [comment]
> > I understand that lxqt is independent, it's still a shame that obconf-qt doesn't really work anymore.
> 
> I suggest you make yourself a developer and be a new contributor to obconf-qt.

That not a problem. I can become the mantainer of obconf-qt. Just @ me at the new issues.

**Comment by tsujan** [comment]
@zhrexl, thanks!

**Comment by GreenLunar** [comment]
> Thats not a problem. I can become the mantainer of obconf-qt. Just @ me at the new issues.

Great. I'll send you feedbacks from using ObConf on a touchscreen if needed.
