### ISSUE TITLE
[Bug] Sidebar too small

### ISSUE THREAD

**Issue by libalis** [lxqt/obconf-qt#192]
![ObConf-Qt](https://user-images.githubusercontent.com/45124869/154604771-ec053054-3583-4044-ab81-4dfb240fa275.png)
As you can see on the screenshot, the text does not fit in.
A possible solution would be to check the needed size of the sidebar at start-up.
I am against a flexible sidebar.

##### System Information
* Distribution & Version: openSUSE Tumbleweed
* Kernel: 5.16.5
* Qt Version: 5.15.2
* libqtxdg Version: 1.0.0
* lxqt-build-tools Version: 1.0.0
* Package version: 0.16.1

**Comment by tsujan** [comment]
→ https://github.com/lxqt/obconf-qt/issues/191#issuecomment-1044040484

**Comment by GreenLunar** [comment]
> A possible solution would be to check the needed size of the sidebar at start-up.

Good idea!

**Comment by tsujan** [comment]
Fixed by https://github.com/lxqt/obconf-qt/commit/160fd83480684980acadc0bf562a3caf7583aec5
