### ISSUE TITLE
Text is cut off on the side list

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/obconf-qt#197]
This bug may be only for my setup, but currently the side-pane is too small for the text. I've attached an image to clearly explain:

![obconf-qt-screenshot](https://user-images.githubusercontent.com/96850319/157825869-1b141f39-489c-41a2-bdc5-8dbc5483e2e1.png)

##### Expected Behavior
All text is displayed even at the smallest window size.

##### Current Behavior
Text is cut off.

##### Context
Accessibility 

##### System Information
* obconf-qt version: 06fa776
* Kernel: linux 5.16.13.arch1-1
* qt5-base version: 5.15.3+kde+r133-1
* lxqt-build-tools version: 0.10.0-1

**Comment by palinek** [comment]
Duplicate #192

**Comment by tsujan** [comment]
@ianfarrell47, please also read https://github.com/lxqt/obconf-qt/issues/191#issuecomment-1044040484

I think we really need to archive this repository.

**Comment by stefonarch** [comment]
We receive still quite a lot attention for this application, users find it shipped as it is in distro. 
So maybe just some fix for this sidepanel width wouldn't hurt nobody IMO.
```
diff --git a/src/obconf.ui b/src/obconf.ui
index 311cf5a..7fbf2c7 100644
--- a/src/obconf.ui
+++ b/src/obconf.ui
@@ -6,10 +6,16 @@
    <rect>
     <x>0</x>
     <y>0</y>
-    <width>595</width>
-    <height>578</height>
+    <width>1000</width>
+    <height>720</height>
    </rect>
   </property>
+  <property name="minimumSize">
+   <size>
+    <width>1000</width>
+    <height>720</height>
+   </size>
+  </property>
   <property name="windowTitle">
    <string>Window Manager Preferences</string>
   </property>
```

**Comment by tsujan** [comment]
Adding to widths in the ui file doesn't fix it; it just hides the problem in some cases. But, of course, it can be fixed completely.

I know that this app may be used by many but, first, it doesn't have an active developer and, second, LXQt doesn't favor any WM now.

**Comment by tsujan** [comment]
OK, I'll fix it when I find the time, but I won't give it priority.

**Comment by ianfarrell47** [comment]
I found a similar issue in a maintained LXQt repo - lxqt-config.
Specifically lxqt-config-session.
Too minor to create an issue on lxqt-config but because it's the same class of problem I'm posting it here, despite not being obconf-qt.
![lxqt-config-session](https://user-images.githubusercontent.com/96850319/157875215-f9890693-864f-4046-988b-e1c2ce184cef.png)
