### ISSUE TITLE
LXQt team license is GPL-2, *not* GPL-2+, is that correct?

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/obconf-qt#210]
While updating the copyright file for obconf-qt, I noticed that, while much of the code in obconf-qt is licensed as GPL-2+, the main copyright of the software (for parts copyrighted by the LXQt team) is GPL-2 only. I suspect this is an oversight or a typo, but as GPL-2 is more restrictive than GPL-2+, I am currently assuming that GPL-2 was intentional, so that I don't accidentally mess up the licensing information.

Is it intentional to only use GPL-2 as the license, not GPL-2+?

**Comment by stefonarch** [comment]
@yan12125 You have some idea about this?
@tsujan Another release for the translations, it's more than a year?

**Comment by tsujan** [comment]
No objection to releasing 0.16.3 from me.
