### ISSUE TITLE
Error on compile on Fedora Rawhide

### ISSUE THREAD

**Issue by farchord** [lxqt/obconf-qt#224]
##### Steps to Reproduce (for bugs)

1. Compile obconf-qt on Fedora Rawhide

##### Context

This issue stops us from compiling obconf-qt on the next version of Fedora (Rawhide).

##### System Information

* Distribution & Version:  Fedora 40 (Rawhide)
* Kernel: 6.8.0-0.rc0.20240110gitab27740f7665
* Qt Version: 5.15.12
* libqtxdg Version: 3.12.0
* lxqt-build-tools Version: 0.13.0
* Package version: 0.16.3

The short of the error is as follows:

/builddir/build/BUILD/obconf-qt-0.16.3/src/obconf-qt.cpp:233:36: error: invalid conversion from ‘const xmlError*’ {aka ‘const _xmlError*’} to ‘xmlErrorPtr’ {aka ‘_xmlError*’} [-fpermissive]
  233 |     xmlErrorPtr e = xmlGetLastError();
      |                     ~~~~~~~~~~~~~~~^~
      |                                    |
      |                                    const xmlError* {aka const _xmlError*}

Attaching the whole build log as well.

Thank you!
[build.log](https://github.com/lxqt/obconf-qt/files/13920999/build.log)

**Comment by tsujan** [comment]
Does replacing the line

https://github.com/lxqt/obconf-qt/blob/d4f36e2dea34c74a7683fcf8ef5461e1542fa812/src/obconf-qt.cpp#L233

with

```c++
const xmlError *e = xmlGetLastError();
```

fix the problem? I can't test because I'm on Wayland.

**Comment by stefonarch** [comment]
I get the same error now on arch, the patch resolves it.
Why should wayland matter for compile btw?

**Comment by tsujan** [comment]
> Why should wayland matter for compile btw?

Not for compilation but for running and testing — at least here, it crashes on Wayland.

**Comment by stefonarch** [comment]
> at least here, it crashes on Wayland.

Ok, but here it opens fine with `QT_QPA_PLATFORM=xcb obconf-qt ` and looks working, changed theme to test.

**Comment by stefonarch** [comment]
Obconf-qt is working fine I see, go ahead. There are no new translations, but some have been merged after the last release, nothing to merge.

**Comment by tsujan** [comment]
> nothing to merge.

What about https://github.com/lxqt/obconf-qt/pull/219?

**Comment by stefonarch** [comment]
I've lost interest somehow in this, as it's not possible for most lxqt apps.
