### ISSUE TITLE
Possible future keybind support ?

### ISSUE THREAD

**Issue by luffah** [lxqt/obconf-qt#38]
Hello, i just have a question linked to a possible improvement.

Will obconf-qt try to manage keybinds ? (i see lxhotkey still in GTK)

As a possible user and contributor, i doesn't understand what will be the future of LXQT. (i haven't find any Human Interface Guide for the project nor a clear choice about the Window Manager)

**Comment by tsujan** [comment]
obconf-qt  is just Openbox configuration tool and Openbox isn't a part of LXQt -- personally, I never use it.

> what will be the future of LXQT

Not being a fortune teller, I can tell that LXQt is being developed actively and relatively fast, while it's kept light, fast and "classic".

> nor a clear choice about the Window Manager

Because LXQt is modular and you could use any window manager that's DE independent: Openbox, KWin, Compiz-reloaded+Emerald, xfwm4,... but not, for example, Enlightenment.

**Comment by tsujan** [comment]
Closing because LXQt doesn't ship an Openbox config anymore, although obconf-qt and Openbox can be used with it.

**Comment by redtide** [comment]
Just seen this, but even if too late: IIUC obconf-qt respect the original obconf configuration UI using Qt instead GTK, with some new features (but regarding the WM, not the shortcut keys). I'm still using openbox as WM and these days I was searching some UI to configure keys too, originally thinking that I could add that feature to obconf-qt but I found [obkey](https://github.com/nsf/obkey) and a bit more [updated git version](https://github.com/stevenhoneyman/obkey) used on AUR. Maybe I'll try to create a new obkey-qt instead. Anyone reading this interested to help me in this by chance?

**Comment by luffah** [comment]
@redtide 
> … but I found [obkey](https://github.com/nsf/obkey) and a bit more [updated git version](https://github.com/stevenhoneyman/obkey) used on AUR.

obkey have a more recent version that i maintained some years ago
https://github.com/luffah/obkey

It is now abandonned from all contributors i know (nsf, steevehoneyman, and me). I'll be happy to mention a newer version in my Readme if mentionned in issues.
